# === WRITE MODEL (PostgreSQL) ===
spring.datasource.write.jdbc-url=jdbc:postgresql://localhost:5432/eventmaster_db
spring.datasource.write.username=eventmaster
spring.datasource.write.password=password
spring.datasource.write.driver-class-name=org.postgresql.Driver

# === READ MODEL (CockroachDB) ===
spring.datasource.read.jdbc-url=jdbc:postgresql://localhost:26257/defaultdb?sslmode=disable
spring.datasource.read.username=root
spring.datasource.read.password=
spring.datasource.read.driver-class-name=org.postgresql.Driver

# === Konfiguracja JPA (globalna) ===
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# === Konfiguracja Flyway ===
spring.flyway.url=${spring.datasource.write.jdbc-url}
spring.flyway.user=${spring.datasource.write.username}
spring.flyway.password=${spring.datasource.write.password}
spring.flyway.locations=classpath:db/migration

server.port=8080
management.endpoint.health.show-details=always
